apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-cluster-01
  namespace: bj-cloudgo
  labels:
    name: redis-cluster-01
spec:
  replicas: 1
  selector:
    name: redis-cluster-01
  template:
    metadata:
      labels:
        name: redis-cluster-01
    spec:
      hostNetwork: true
      nodeSelector:
        redis-cluster: master01
      containers:
      - image: 10.16.117.252/redis-cluster/redis-cluster:1.1.4.4
        name: redis-cluster-01
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
          hostPort: 8001
        - containerPort: 8004
          hostPort: 8004
        command: ["/bin/bash","-c","/opt/run.sh cluster-01"]
        volumeMounts:
        - name: redis-cluster-01
          mountPath: "/opt/redis_cluster"
      volumes:
        - name: redis-cluster-01
          rbd:
            monitors:
              - 10.130.129.231:6789
              - 10.130.129.232:6789
              - 10.130.129.232:6789
            pool: cloudgo
            image: redis-cluster-01
            user: admin
            keyring:
            secretRef:
            fsType: ext4
                                  
